server:
  port: 8080
  servlet:
    context-path: /Blog
    session:
      timeout: 200m
    encoding:
      enabled: true
      charset: UTF-8
      force: true
    jsp:
      init-parameters:
        development: true
  tomcat:
    uri-encoding: UTF-8
    threads:
      # tomcat最大线程数，默认为200
      max: 200
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 20

spring:
  profiles:
    active: '@profiles.active@'
  # 文件上传
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  web:
    resources:
      static-locations: classpath:/assets/,classpath:/static/
      add-mappings: true
  mvc:
    static-path-pattern: /**
    view:
      prefix: /views/
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
    converters:
      preferred-json-mapper: fastjson
  #数据库配置信息
  datasource:
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      #testOnBorrow确保每次能获取到可用连接
      test-while-idle: true
      test-on-borrow: false
      #如果为true（默认false），当应用使用完连接，连接池回收连接时会判断该连接是否还可用
      test-on-return: false
# mybatis配置
mybatis:
  mapper-locations: classpath:**/mapper/*.xml
  type-aliases-package: com.fit.entity
  configuration:
    default-executor-type: REUSE
    use-generated-keys: true
    cache-enabled: true

logging:
  file:
    path: ./target/logs